version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      #- USER=username #optional
      #- PASS=password #optional
    volumes:
      - /media/data/downloads:/downloads
      - /media/data/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=#optional
    volumes:
      - /media/data/appdata/jackett:/config
      - /media/data/watch:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - UMASK_SET=022 #optional
    volumes:
      - /media/data/appdata/radarr:/config
      - /media/data/public/Movies:/movies
      - /media/data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - UMASK_SET=022 #optional
    volumes:
      - /media/data/appdata/sonarr:/config
      - /media/data/public/TV:/tv
      - /media/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - UMASK_SET=022 #optional
    volumes:
      - /media/data/appdata/lidarr:/config
      - /media/data/public/Music:/music
      - /media/data/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - /media/data/appdata/lazylibrarian:/config
      - /media/data/downloads:/downloads
      - /media/data/public/Library/ebooks:/ebooks
      - /media/data/public/Library/abooks:/abooks
      - /media/data/public/Books:/books
    ports:
      - 5299:5299
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - TZ=Asia/Manila
      - VERSION=docker
      #- PLEX_CLAIM=claim-1234567890
    volumes:
      - /media/data/appdata/plex:/config
      - /media/data/public/TV:/tv
      - /media/data/public/Movies:/movies
    ports:
      - "32400:32400/tcp"
      - "1900:1900/udp"
      - "3005:3005/tcp"
      - "5353:5353/udp"
      - "8324:8324/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
    restart: unless-stopped
